export const IMAGES: Record<string, string> = {
  NAVIGATION: "Navigation",
  AVATAR: "Avatar",
  BADGE: "Badge",
  BUTTON: "Button",
  CARD: "Card",
  CHIP: "Chip",
  DIALOG: "Dialog",
  POPOVER: "Popover",
  BREADCRUMBS: "Breadcrumbs",
  CHECKBOX: "Checkbox",
  PROGRESSBAR: "Progress Bar",
  SELECT: "Select",
  TOAST: "Toast",
  TOOLTIP: "Tooltip",
  DATEPICKER: "Datepicker",
  DRAWER: "Drawer",
  DROPDOWN: "Dropdown",
  EMPTY: "Empty",
  LIST: "List",
  HEADER: "Header",
  PAGINATION: "Pagination",
  SIDEBAR: "Sidebar",
  RANGE: "Range",
  ICON: "Icon",
  FORM: "Form",
  TABLE: "Table",
  TOGGLE: "Toggle",
  SPINNER: "Spinner",
  RADIOBUTTON: "Radio Button",
  BUTTONGROUP: "Button Group",
  TABS: "Tabs",
  CODE: "Code",
  TEXTFIELD: "Text field",
  INLINEMESSAGE: "Inline message",
  TEXTAREA: "Text area",
  TABLETREE: "Table tree",
  MENU: "Menu",
  SEARCH: "Search",
  ALERTBANNER: "Alert banner",
  ACCORDION: "Accordion",
  AUTOCOMPLETE: "Autocomplete",
  LINK: "Link",
  ACTIONBAR: "Action bar",
  TRAY: "Tray",
  HELPTEXT: "Help text",
  LABEL: "Label",
  NAVIGATIONBAR: "Navigation bar",
  DIVIDER: "Divider",
};

export const LINKS = [
  {
    path: "/blog",
    title: "Blog",
    isDisabled: true,
  },
  {
    path: "/figma",
    title: "Figma",
    isDisabled: true,
  },
  {
    path: "/components",
    title: "Components",
    isDisabled: false,
  },
  {
    path: "/design-systems",
    title: "Design Systems",
    isDisabled: false,
  },
];

export const COMPONENT_TYPES = [
  {
    label: "Overlays",
    value: "Overlays",
  },
  {
    label: "Data",
    value: "Data",
  },
  {
    label: "Input",
    value: "Input",
  },
  {
    label: "Status",
    value: "Status",
  },
  {
    label: "Navigation",
    value: "Navigation",
  },
  {
    label: "Loading",
    value: "Loading",
  },
  {
    label: "Messaging",
    value: "Messaging",
  },
  {
    label: "Action",
    value: "Action",
  },
  {
    label: "Images",
    value: "Images",
  },
  {
    label: "Layout",
    value: "Layout",
  },
  {
    label: "Form",
    value: "Form",
  },
];
