export const IMAGES: Record<string, string> = {
  NAVIGATION: "Navigation",
  AVATAR: "Avatar",
  BADGE: "Badge",
  BUTTON: "Button",
  CARD: "Card",
  CHIP: "Chip",
  DIALOG: "Dialog",
  POPOVER: "Popover",
  BREADCRUMBS: "Breadcrumbs",
  CHECKBOX: "Checkbox",
  PROGRESSBAR: "Progress Bar",
  SELECT: "Select",
  TOAST: "Toast",
  TOOLTIP: "Tooltip",
  DATEPICKER: "Datepicker",
  DRAWER: "Drawer",
  DROPDOWN: "Dropdown",
  EMPTY: "Empty",
  LIST: "List",
  HEADER: "Header",
  PAGINATION: "Pagination",
  SIDEBAR: "Sidebar",
  RANGE: "Range",
  ICON: "Icon",
  FORM: "Form",
  TABLE: "Table",
  TOGGLE: "Toggle",
};

export const LINKS = [
  {
    path: "/blog",
    title: "Blog",
    isDisabled: true,
  },
  {
    path: "/figma",
    title: "Figma",
    isDisabled: true,
  },
  {
    path: "/components",
    title: "Components",
    isDisabled: true,
  },
  {
    path: "/design-systems",
    title: "Design Systems",
    isDisabled: false,
  },
];
